networks:
  shared:
    name: shared
  public:
    name: public
    internal: false
services:
  gitea:
    container_name: gitea
    image: gitea/gitea:latest
    restart: always
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - GITEA__server__SSH_PORT=222
    volumes:
      - gitea:/data
      - /etc/hostname:/etc/hostname:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - shared
      - public
    ports:
      - 127.0.0.1:3000:3000
      - 222:22
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - shared
    volumes:
      - postgres:/var/lib/postgres/data
volumes:
  gitea:
    driver: local
  postgres:
    driver: local
