name: "Build closures with Colmena"
on:
  pull_request:
  push:
jobs:
  generate_matrix:
    name: "Generate hive list"
    runs-on: ubuntu-latest
    outputs:
       matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: actions/checkout@v4
      - id: matrix
        name: "Run nix eval to generate node list"
        run: |
          JSON=$(nix eval .#colmena --apply 'with builtins; x: filter (f: !elem f [ "defaults" "meta" ]) (attrNames x)' --json)
          echo "matrix=$JSON" >> $GITHUB_OUTPUT
  build:
    name: "Build node"
    needs: generate_matrix
    strategy:
      # each closure is independent from each other
      fail-fast: false
      matrix:
        node: ${{ fromJSON(needs.generate_matrix.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install QEMU
      run: |
          sudo apt update -q -y
          sudo apt install -q -y binfmt-support qemu-efi qemu-system-aarch64 qemu-user-static
    - uses: DeterminateSystems/nix-installer-action@v4
      name: Install Nix
      with:
        extra-conf: |
          extra-platforms = aarch64-linux i686-linux
          trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          trusted-substituters = https://cache.garnix.io https://cache.nixos.org
          substituters = https://cache.garnix.io https://cache.nixos.org
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: cachix/cachix-action@v14
      name: Setup cachix
      with:
        name: lychee
        authToken: '${{ secrets.CACHIX_KEY }}'
    - name: Build ${{ matrix.node }}
      run: |
        nix run nixpkgs#colmena -- build --no-build-on-target -v --on ${{ matrix.node }}
